package live.autu.ctcms.common.model;

import live.autu.ctcms.common.model.base.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
	
}
